services:
  postgres:
    image: postgres:14-alpine
    container_name: cementerio-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cementerio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:latest
    container_name: cementerio-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data:
