version: '3.8'

services:
  sqlserver-checa:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-checa
    ports:
      - "${MSSQL_PORT}:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
    volumes:
      - sql_data:/var/opt/sqlserver-checa
      - ./init.sql:/init.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $${SA_PASSWORD} -Q 'SELECT 1' -C -N" ]
      interval: 5s
      timeout: 5s
      retries: 20
    entrypoint: >
      /bin/bash -c "
        /opt/mssql/bin/sqlservr &

        echo 'Esperando que SQL Server esté listo...';

        for i in {1..30}; do
          /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $${SA_PASSWORD} -Q 'SELECT 1' -C -N && break
          sleep 1
        done

        echo 'Ejecutando script SQL...';
        /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $${SA_PASSWORD} -i /init.sql -C -N

        wait
      "
    env_file:
      - .env
    networks:
      - cementerio-net

  app:
    build:
      context: .
      dockerfile: gad_checa_gestion_cementerio/Dockerfile
    ports:
      - "3005:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - DB_CONNECTION_STRING=Server=sqlserver-checa;Database=${MSSQL_DATABASE};User=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;MultipleActiveResultSets=true;ConnectRetryCount=5;ConnectRetryInterval=10;
    depends_on:
      sqlserver-checa:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - cementerio-net
    volumes:
      - ./data-protection-keys:/app/keys:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: >
      /bin/bash -c "
        echo 'Esperando que SQL Server esté completamente listo...';
        sleep 10;
        dotnet gad_checa_gestion_cementerio.dll
      "

volumes:
  sql_data:
    driver: local
  data-protection-keys:
    driver: local

networks:
  cementerio-net:
    driver: bridge