version: '3.8'

services:
  sqlserver-checa:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-checa
    ports:
      - "${MSSQL_PORT}:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
    volumes:
      - sql_data:/var/opt/sqlserver-checa
      - ./init.sql:/init.sql:ro  # Montamos el archivo de inicialización
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $${SA_PASSWORD} -Q 'SELECT 1' -C -N" ]
      interval: 5s
      timeout: 5s
      retries: 20
    entrypoint: >
      /bin/bash -c "
        /opt/mssql/bin/sqlservr &

        echo 'Esperando que SQL Server esté listo...';

        for i in {1..30}; do
          /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $${SA_PASSWORD} -Q 'SELECT 1' -C -N && break
          sleep 1
        done

        echo 'Ejecutando script SQL...';
        /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $${SA_PASSWORD} -i /init.sql -C -N

        wait
      "
    env_file:
      - .env
    networks:
      - cementerio-net

  app:
    build:
      context: .
      dockerfile: gad_checa_gestion_cementerio/Dockerfile
    ports:
      - "3005:8080"
    environment:
      - DB_CONNECTION_STRING=Server=sqlserver-checa;Database=${MSSQL_DATABASE};User=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;  # ¡Nueva variable!
    depends_on:
      sqlserver-checa:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - cementerio-net
    volumes:
      - ./data-protection-keys:/app/keys
volumes:
  sql_data:
  dataprotection-keys:
networks:
  cementerio-net:
    driver: bridge